const express = require('express');
const orderController = require('../controller/OrderController');
const verifyUser = require('../middleware/AuthMiddleware');
const router = express.Router();
router.post('/create',verifyUser,orderController.create);
// router.post('/create',orderController.create);
router.get('/find-by-id/:id',verifyUser,orderController.findById);
router.delete('/delete-by-id/:id',verifyUser,orderController.deleteById);
router.put('/update/:id',verifyUser,orderController.update);
router.get('/find-all',verifyUser,orderController.findAll);
router.get('/find-count',verifyUser,orderController.findCount);
router.get('/find-income',verifyUser,orderController.findIncome);
module.exports = router;